M48
; DRILL file {KiCad 7.0.9} date Mon Jan  8 23:19:34 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-08T23:19:34+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0433
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.0591
%
G90
G05
T1
X3.7Y-3.4
X3.7Y-4.0
X4.1Y-3.4
X4.1Y-4.0
T2
X4.3Y-3.4
X4.3Y-4.0
X4.4Y-3.4
X4.4Y-4.0
T3
X4.6Y-3.3114
X4.6Y-3.4886
X4.6Y-3.9228
X4.6Y-4.1
X4.8559Y-3.3114
X4.8559Y-3.4886
X4.8559Y-3.9228
X4.8559Y-4.1
T4
X5.1Y-3.7
X5.9067Y-3.7
T0
M30
